### PR TITLE
Background

### PR DESCRIPTION
**Pull request by sanderau**
Added my pictures of my designs and add the files to have a new backgroud

### CODE REVIEW

**Comment by Friction-less-development** [comment]
The current css overwrites some of the css in master for the cards. See if you can retain the masters css for those.

Also background might be better if it looped, but it gives the right impression as is.

**Comment by sammysamx20** [comment]
I'll merge it and check it out if there is any errors.

**Comment by sammysamx20** [comment]
Yeah the cards look really big and kinda overlap the buttons. This is just simple CSS problems that can be fixed.

**Comment by sammysamx20** [comment]
Hey I notice you fixed them and the cards are normal sized now. The background also gives a good look and lets the buttons and cards pop out for usability

**Pull request merged**
