### PR TITLE
Implemented cards

### PR DESCRIPTION
**Pull request by Friction-less-development**

### CODE REVIEW

**Comment by Bradford-Wong** [comment]
Awesome job, it looks amazing.

**Comment by sammysamx20** [comment]
Hey I just checked it out and it looks really good. Like I said in the issue the buttons and cards overlap once we get to like row 7 but other wise its great. It should just be really simple css fixes.

**Comment by Friction-less-development** [comment]
Alright, I'll fix that up.

**Comment by sanderau** [comment]
Yo, these cards look fantastic. The go very well with the whole aesthetic of the game. My only input is we have a lot of dead space on out UI so possibly making these larger would let us take advantage of the entire real estate. This however would have to be a group effort and we would have to change everything to be a different size and on a different part of the board, so it is not really realistic. Great job my man looks fantastic 💯

**Pull request merged**
