### PR TITLE
Added drop down menu

### PR DESCRIPTION
**Pull request by Bradford-Wong**

### CODE REVIEW

**Comment by sammysamx20** [comment]
I hope the revert and the drop down menu works

**Comment by sammysamx20** [comment]
It looks good. I think we have to revert some of our commits.

**Comment by sammysamx20** [comment]
Hey I was checking your pull down menu and it works. I changed the move button to look more clearer on my side. Also I think that option was a great part of the learn ability for the user and makes it easier than typing in any number. However, I don't know if it is an error on your part or the code that was provided from the teacher, but it seems we are able to move cards even though some spots aren't empty. I don't know if you should look at that or not but definitely something to try out.

**Comment by Bradford-Wong** [comment]
Yeah, I noticed that too. I'm thinking that the code doesn't have all the input validation implemented yet.

**Comment by sanderau** [comment]
Hey man the pull down menus look great, and I think they are very well placed as far as UI and UX go. The only thing I would possible change is change the physical numbers to the spelled out version i.e. ("one", "two", etc). I would also change the text to a different color so it pops a lot better. The user can probably find it because of the move button, but the more visible the better. Overall it is a great addition to our game.

**Pull request merged**
